### ISSUE TITLE
Space character not working when search for a Surah

### ISSUE THREAD

**Issue by zaher-aa** [EL-MEHDI-ESSAADI/Quran-Player#1]
### Hi Mehdi, you did a great job working on this wonderful app, may Allah bless you, my brother.
But I've noticed a problem that appears when searching for a Surah while another Surah is playing.
For example, if I want to search for Surah `Al Fatiha` while playing Surah `Al-Baqara` for example, the first two letters will be written successfully, but when I reach the space character, the audio player will be toggled on/off and no space character will be written.

I hope you solve it soon.
I loved your website very much, keep up the good work 😍

**Comment by EL-MEHDI-ESSAADI** [comment]
that's true, hhhh I add event listener to the window to listen to key down:
if the player is playing and the user press space, I stop the player and prevent the default event from happening,
and that's the cause of spacing not working while soruh playing.
I will try to fix that now and thanks for submitting the first issue in my github profile, the first is always special 😄

**Comment by zaher-aa** [comment]
> that's true, hhhh I add event listener to the window to listen to key down: if the player is playing and the user press space, I stop the player and prevent the default event from happening, and that's the cause of spacing not working while soruh playing. I will try to fix that now and thanks for submitting the first issue in my github profile, the first is always special smile

I've solved the problem, if you can add me to your repository to push my pull request I'll be very happy to contribute to your website ☺️

**Comment by EL-MEHDI-ESSAADI** [comment]
I fixed the problem with add this condition:
if document.activeElement === header.headerInput don't do anything.
Feel free bro to contribute.
I'm so happy bro I got my first issue and someone liked my project that much and want to contribute, I appreciate you.

**Comment by zaher-aa** [comment]
I've opened a pull-request that solves the problem bro
